/// Calendar dimension used for filtering, grouping, and time-intelligence analysis.
table 'Dim Date'
	lineageTag: c3451eda-6565-4ff3-900e-e28b201bf025
	dataCategory: Time

	/// Surrogate key for the calendar date.
	column 'Date Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f992ed40-2a32-4f54-997e-98484773443b
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	/// Calendar date used for relationships and time intelligence.
	column Date
		dataType: dateTime
		isUnique
		formatString: Long Date
		lineageTag: 7b039894-65d5-4e2d-ad30-1fcd0c579cc3
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Calendar year number.
	column Year
		dataType: int64
		formatString: 0
		lineageTag: 33aacbe3-34fe-4110-ab7e-b9a7f8af6d2c
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	/// Calendar quarter label.
	column Quarter
		dataType: string
		lineageTag: 7854bdb7-bb02-4ed4-8933-d5463ed9bd27
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	/// Month number within the calendar year.
	column 'Month Number'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a844d68c-1c67-4bf2-84dc-1e1da65c1e26
		summarizeBy: none
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	/// Month name used for slicers and labels.
	column 'Month Name'
		dataType: string
		lineageTag: 69e27c28-86ba-4c3d-be92-bd405054083b
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: 'Month Number'

		annotation SummarizationSetBy = Automatic

	/// Calendar month grain used for chronological trend analysis.
	column 'Year Month'
		dataType: dateTime
		formatString: MMM yyyy
		lineageTag: ef03afce-b8cd-4a9c-a1db-b8b818bdc190
		summarizeBy: none
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataRootFolder & "\dim_date.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DateKey", Int64.Type}, {"Date", type date}, {"Year", Int64.Type}, {"Quarter", type text}, {"MonthNumber", Int64.Type}, {"MonthName", type text}, {"YearMonth", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

