/// Transaction-level sales fact table used for revenue, cost, volume, and margin analysis.
table 'Fact Sales'
	lineageTag: 8ed44def-41ac-4706-ac8c-ad64c60ebdce

	/// Total sales amount across the current filter context.
	measure 'Total Sales' = SUM('Fact Sales'[Sales Amount])
		formatString: #,0
		displayFolder: Key Metrics
		lineageTag: eac42d27-d78e-4dce-8a62-e8101600f288

	/// Total cost amount across the current filter context.
	measure 'Total Cost' = SUM('Fact Sales'[Cost Amount])
		formatString: #,0
		displayFolder: Key Metrics
		lineageTag: 4f01cb73-a8b1-4881-be9e-4ab9e696af6e

	/// Difference between sales amount and total cost.
	measure 'Gross Margin' = [Total Sales] - [Total Cost]
		formatString: #,0
		displayFolder: Key Metrics
		lineageTag: ef59bc2c-973c-40cf-b245-a2edf0ec7d8d

	/// Gross margin as a share of sales amount.
	measure 'Gross Margin %' = DIVIDE([Gross Margin], [Total Sales])
		formatString: 0.0%
		displayFolder: Key Metrics
		lineageTag: 65ecbc8a-c834-47cb-bf24-dc7be51c8ac2

	/// Total units sold in the current filter context.
	measure 'Total Units' = SUM('Fact Sales'[Units])
		formatString: #,0
		displayFolder: Key Metrics
		lineageTag: e9b626ef-49b4-4b28-a023-0ec1bbc5adf5

	/// Distinct count of orders in the current filter context.
	measure 'Order Count' = DISTINCTCOUNT('Fact Sales'[Order ID])
		formatString: #,0
		displayFolder: Key Metrics
		lineageTag: 8395cda1-74dd-4315-aef5-0c196d3f6ddc

	/// Average sales amount per distinct order.
	measure 'Average Order Value' = DIVIDE([Total Sales], [Order Count])
		formatString: #,0
		displayFolder: Key Metrics
		lineageTag: d9b8ff1d-d820-4971-b1af-b98cb61c4009

	/// Unique identifier for each sales order in the sample fact table.
	column 'Order ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 295fdd76-8181-408a-a3c4-de7ef4cc654c
		summarizeBy: count
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	/// Surrogate key linking each sale to the date dimension.
	column 'Date Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 84785fe5-9302-4b2e-aecf-5dd0092731a2
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	/// Surrogate key linking each sale to the region dimension.
	column 'Region Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e0950532-ccf0-49e8-8bae-c1fc2c20f6a3
		summarizeBy: none
		sourceColumn: RegionKey

		annotation SummarizationSetBy = Automatic

	/// Surrogate key linking each sale to the product dimension.
	column 'Product Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8bc02cdf-7daa-45b0-84fc-d83dd152c7ee
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	/// Surrogate key linking each sale to the channel dimension.
	column 'Channel Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 587fac71-704f-4116-ba82-2e1ab7bbbacf
		summarizeBy: none
		sourceColumn: ChannelKey

		annotation SummarizationSetBy = Automatic

	/// Number of units sold for the transaction.
	column Units
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 1f6d0625-5623-458f-8cab-47c857256712
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

	/// Gross sales amount recorded for the transaction.
	column 'Sales Amount'
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 1cb70a64-c821-4cee-8d86-8c33c0676172
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

	/// Total cost amount associated with the transaction.
	column 'Cost Amount'
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 81e16d82-e8b2-4470-8afe-822d63f7e587
		summarizeBy: sum
		sourceColumn: CostAmount

		annotation SummarizationSetBy = Automatic

	partition fact_sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataRootFolder & "\fact_sales.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrderID", Int64.Type}, {"DateKey", Int64.Type}, {"RegionKey", Int64.Type}, {"ProductKey", Int64.Type}, {"ChannelKey", Int64.Type}, {"Units", Int64.Type}, {"SalesAmount", Int64.Type}, {"CostAmount", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

