/// Optional bridge table for row-level security demonstrations by region.
table 'Security Region Access'
	isHidden
	lineageTag: 3d907769-d3eb-4ae0-a4e9-78dad13e879a

	/// User principal name allowed to access the mapped region in the optional RLS scenario.
	column 'User Principal Name'
		dataType: string
		isHidden
		lineageTag: f0238e38-4f1a-4a9d-a545-3302185d5647
		summarizeBy: none
		sourceColumn: UserPrincipalName

		annotation SummarizationSetBy = Automatic

	/// Region granted to the user in the optional RLS scenario.
	column Region
		dataType: string
		isHidden
		lineageTag: a7d83855-d9ad-4085-9564-a7ef05e484df
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition security_region_access = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataRootFolder & "\security_region_access.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"UserPrincipalName", type text}, {"Region", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

